# **Telecom Churn Prediction Case Study**

In the telecommunication industry, customers tend to change operators if not provided with attractive schemes and offers. It is very important for any telecom operator to prevent the present customers from churning to other operators. As a data scientist, your task in this case study would be to build an ML model which can predict if the customer will churn or not in a particular month based on the past data.

#### **Objectives**

The main goal of the case study is to build ML models to predict churn. The predictive model that youâ€™re going to build will the following purposes:

- It will be used to predict whether a high-value customer will churn or not, in near future (i.e. churn phase). By knowing this, the company can take action steps such as providing special plans, discounts on recharge etc.

- It will be used to identify important variables that are strong predictors of churn. These variables may also indicate why customers choose to switch to other networks.

- Even though overall accuracy will be your primary evaluation metric, you should also mention other metrics like precision, recall, etc. for the different models that can be used for evaluation purposes based on different business objectives. For example, in this problem statement, one business goal can be to build an ML model that identifies customers who'll definitely churn with more accuracy as compared to the ones who'll not churn. Make sure you mention which metric can be used in such scenarios.

- Recommend strategies to manage customer churn based on your observations.

#### **Import Libraries**

In [1]:
import numpy as np
import pandas as pd

# Importing plot Libraries
import matplotlib.pyplot as plt 
import seaborn as sns

# Importing Data Processing Libraries
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FeatureUnion
from sklearn.preprocessing import StandardScaler
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# Importing ML Libaries
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier

# Import ModelEvaluation Libraries
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score

#### **Adjusting Output Settings**

In [2]:
# Ignore version warnings
import warnings
warnings.filterwarnings('ignore')

# Setting Pandas Display options
pd.set_option("display.max_columns", 500)
pd.set_option('display.max_rows', 1000)
pd.set_option('max_colwidth',100)

# Print all the output in Notebook instead of ...
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

#### **Custom Functions for Univariant and BiVariant Plots, Treating the Outliers**

In [3]:
def data_type(var):
    if var.dtype == np.int64 or var.dtype == np.float64: return 'num'
    elif var.dtype == 'category': return 'cat'

    
def univar_plot_byCheckingColTyp(df, col, vartype , hue = None):
       
    sns.set(style="darkgrid")
    
    if vartype == 0:
        fig, ax = plt.subplots(nrows=1, ncols=2, figsize=(10,6))
        
        ax[0].set_title("Box Plot")
        sns.boxplot(data=df, x=col, ax=ax[0], orient='v')
        
        ax[1].set_title("Distribution Plot")
        sns.distplot(df[col],ax=ax[1])      
    elif vartype == 1:
        temp = pd.Series(data = hue)
        fig, ax = plt.subplots()
        width = len(df[col].unique()) + 6 + 4*len(temp.unique())
        fig.set_size_inches(width , 7)
        ax = sns.countplot(data = df, x=col, order=df[col].value_counts().index, hue=hue) 
        if len(temp.unique()) > 0:
            for p in ax.patches:
                ax.annotate('{:1.1f}%'.format((p.get_height()*100)/float(len(df))), (p.get_x()+0.05, p.get_height()+20))  
        else:
            for p in ax.patches:
                ax.annotate(p.get_height(), (p.get_x()+0.32, p.get_height()+20)) 
        del temp
    else:
        print('Wrong Variable Type is passed, please check.')
        exit
        
    plt.show()
    
    
def univariate(df, col, stats=True):
    
    if data_type(df[col]) == 'num':
        univar_plot_byCheckingColTyp(df, col, 0)
        if stats == True:
            print(df[col].describe())
    
    elif data_type(df[col]) == 'cat':
        univar_plot_byCheckingColTyp(df, col, 1)
        if stats == True:
            print(df[col].value_counts())
            
    else:
        print("Invalid variable passed: either pass a numeric variable or a categorical vairable.")

        
def bivariate(df, var1, var2):
    if data_type(df[var1]) == 'num' and data_type(df[var2]) == 'num':
        sns.regplot(df[var1], df[var2])
    elif (data_type(df[var1]) == 'cat' and data_type(df[var2]) == 'num') or (data_type(df[var1]) == 'num' and data_type(df[var2]) == 'cat'):
        sns.boxplot(df[var1], df[var2])
        
        
## Standard Deviation Outlier Treatment 

def std_dev_cap_outliers(data, k = 10):
    upper_limit = data.mean() + k * data.std()
    lower_limit = data.mean() - k * data.std()
    data[data < lower_limit] = lower_limit
    data[data > upper_limit] = upper_limit
    return data

#### **Data Understanding**

In [4]:
data_dictionary = pd.read_csv('data_dictionary.csv')
data_dictionary

,Acronyms,Description
0,CIRCLE_ID,Telecom circle area to which the customer belongs to
1,LOC,Local calls within same telecom circle
2,STD,STD calls outside the calling circle
3,IC,Incoming calls
4,OG,Outgoing calls
5,T2T,Operator T to T ie within same operator mobile to mobile
6,T2M,Operator T to other operator mobile
7,T2O,Operator T to other operator fixed line
8,T2F,Operator T to fixed lines of T
9,T2C,Operator T to its own call center
10,ARPU,Average revenue per user
11,MOU,Minutes of usage voice calls
12,AON,Age on network number of days the customer is using the operator T network
13,ONNET,All kind of calls within the same operator network
14,OFFNET,All kind of calls outside the operator T network
15,ROAM,Indicates that customer is in roaming zone during the call
16,SPL,Special calls
17,ISD,ISD calls
18,RECH,Recharge
19,NUM,Number
20,AMT,Amount in local currency
21,MAX,Maximum
22,DATA,Mobile internet
23,3G,G network
24,AV,Average
25,VOL,Mobile internet usage volume in MB
26,2G,G network
27,PCK,Prepaid service schemes called PACKS
28,NIGHT,Scheme to use during specific night hours only
29,MONTHLY,Service schemes with validity equivalent to a month
30,SACHET,Service schemes with validity smaller than a month
31,*.6,KPI for the month of June
32,*.7,KPI for the month of July
33,*.8,KPI for the month of August
34,FB_USER,Service scheme to avail services of Facebook and similar social networking sites
35,VBC,Volume based cost when no specific scheme is not purchased and paid as per usage

In [5]:
#Loading the train and test data.

df_train = pd.read_csv('train.csv')
df_test_unseen = pd.read_csv('test.csv')

RESULT_TEST_FILEPATH = './result_Tegbirsingh_Jagadeeshjunjuri.csv'

In [6]:
# Checking Headers
df_train.head()

,id,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,churn_probability
0,0,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,31.277,87.009,7.527,48.58,124.38,1.29,32.24,96.68,2.33,0.00,0.0,0.0,0.00,0.0,0.00,2.23,0.00,0.28,5.29,16.04,2.33,0.00,0.00,0.00,0.00,0.00,0.00,7.53,16.04,2.61,46.34,124.38,1.01,18.75,80.61,0.0,0.00,0.0,0.0,0.0,0.0,0.0,65.09,204.99,1.01,0.0,0.0,0.0,8.20,0.63,0.00,0.38,0.0,0.0,81.21,221.68,3.63,2.43,3.68,7.79,0.83,21.08,16.91,0.00,0.00,0.00,3.26,24.76,24.71,0.00,7.61,0.21,7.46,19.96,14.96,0.0,0.0,0.0,0.0,0.0,0.0,7.46,27.58,15.18,11.84,53.04,40.56,0.0,0.0,0.66,0.0,0.0,0.0,1.11,0.69,0.00,3,2,2,77,65,10,65,65,10,6/22/2014,7/10/2014,8/24/2014,65,65,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1958,0.0,0.0,0.0,0
1,1,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,0.000,122.787,42.953,0.00,0.00,0.00,0.00,25.99,30.89,0.00,0.0,0.0,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,22.01,29.79,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.00,30.73,31.66,0.00,0.0,0.0,0.00,30.73,31.66,1.68,19.09,10.53,1.41,18.68,11.09,0.35,1.66,3.40,3.44,39.44,25.03,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,3.44,39.44,25.04,0.0,0.0,0.01,0.0,0.0,0.0,0.00,0.00,0.00,3,4,5,0,145,50,0,145,50,6/12/2014,7/10/2014,8/26/2014,0,0,0,NaN,7/8/2014,NaN,NaN,1.0,NaN,NaN,145.0,NaN,NaN,0.0,NaN,NaN,1.0,NaN,NaN,145.0,NaN,0.0,352.91,0.00,0.0,3.96,0.0,NaN,122.07,NaN,NaN,122.08,NaN,NaN,0.0,NaN,0,0,0,0,0,0,0,1,0,0,0,0,NaN,1.0,NaN,710,0.0,0.0,0.0,0
2,2,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,60.806,103.176,0.000,0.53,15.93,0.00,53.99,82.05,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.53,12.98,0.00,24.11,0.00,0.00,0.00,0.00,0.00,2.14,0.00,0.00,24.64,12.98,0.00,0.00,2.94,0.00,28.94,82.05,0.0,0.00,0.0,0.0,0.0,0.0,0.0,28.94,84.99,0.00,0.0,0.0,0.0,2.89,1.38,0.00,0.00,0.0,0.0,56.49,99.36,0.00,4.51,6.16,6.49,89.86,25.18,23.51,0.00,0.00,0.00,94.38,31.34,30.01,11.69,0.00,0.00,18.21,2.48,6.38,0.0,0.0,0.0,0.0,0.0,0.0,29.91,2.48,6.38,124.29,33.83,36.64,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.25,2,4,2,70,120,0,70,70,0,6/11/2014,7/22/2014,8/24/2014,70,50,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,882,0.0,0.0,0.0,0
3,3,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,156.362,205.260,111.095,7.26,16.01,0.00,68.76,78.48,50.23,0.00,0.0,0.0,0.00,0.0,1.63,6.99,3.94,0.00,37.91,44.89,23.63,0.00,0.00,0.00,0.00,0.00,8.03,44.91,48.84,23.63,0.26,12.06,0.00,15.33,25.93,4.6,0.56,0.0,0.0,0.0,0.0,0.0,16.16,37.99,4.60,0.0,0.0,0.0,14.95,9.13,25.61,0.00,0.0,0.0,76.03,95.98,53.84,24.98,4.84,23.88,53.99,44.23,57.14,7.23,0.81,0.00,86.21,49.89,81.03,0.00,0.00,0.00,8.89,0.28,2.81,0.0,0.0,0.0,0.0,0.0,0.0,8.89,0.28,2.81,95.11,50.18,83.84,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,2,4,3,160,240,130,110,110,50,6/15/2014,7/21/2014,8/25/2014,110,110,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,982,0.0,0.0,0.0,0
4,4,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,240.708,128.191,101.565,21.28,4.83,6.13,56.99,38.11,9.63,53.64,0.0,0.0,15.73,0.0,0.00,10.16,4.83,6.13,36.74,19.88,4.61,11.99,1.23,5.01,0.00,9.85,0.00,58.91,25.94,15.76,0.00,0.00,0.00,4.35,0.00,0.0,0.00,0.0,0.0,0.0,0.0,0.0,4.35,0.00,0.00,0.0,0.0,0.0,0.00,17.00,0.00,0.00,0.0,0.0,63.26,42.94,15.76,5.44,1.39,2.66,10.58,4.33,19.49,5.51,3.63,6.14,21.54,9.36,28.31,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,21.54,9.36,28.31,0.0,0.0,0.00,0.0,0.0,0.0,0.00,0.00,0.00,13,10,8,290,136,122,50,41,30,6/25/2014,7/26/2014,8/30/2014,25,10,30,6/25/2014,7/23/2014,8/20/2014,7.0,7.0,6.0,25.0,41.0,25.0,7.0,6.0,6.0,0.0,1.0,0.0,175.0,191.0,142.0,390.8,308.89,213.47,0.0,0.00,0.0,0.0,35.00,0.0,0.0,35.12,0.0,0.0,0.0,0.0,0,0,0,7,6,6,0,0,0,0,1,0,1.0,1.0,1.0,647,0.0,0.0,0.0,0

In [7]:
# Checking count of Rows and Columns in Dataset and View List of Data Types and count of columns
print('Train Data Details')
print(df_train.shape)
print(df_train.info(verbose=True))

Train Data Details
(69999, 172)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69999 entries, 0 to 69998
Data columns (total 172 columns):
 #    Column                    Dtype
---   ------                    -----
 0    id                        int64
 1    circle_id                 int64
 2    loc_og_t2o_mou            float64
 3    std_og_t2o_mou            float64
 4    loc_ic_t2o_mou            float64
 5    last_date_of_month_6      object
 6    last_date_of_month_7      object
 7    last_date_of_month_8      object
 8    arpu_6                    float64
 9    arpu_7                    float64
 10   arpu_8                    float64
 11   onnet_mou_6               float64
 12   onnet_mou_7               float64
 13   onnet_mou_8               float64
 14   offnet_mou_6              float64
 15   offnet_mou_7              float64
 16   offnet_mou_8              float64
 17   roam_ic_mou_6             float64
 18   roam_ic_mou_7             float64
 19   roam_ic_mou_8             float64
 20   roam_og_mou_6             float64
 21   roam_og_mou_7             float64
 22   roam_og_mou_8             float64
 23   loc_og_t2t_mou_6          float64
 24   loc_og_t2t_mou_7          float64
 25   loc_og_t2t_mou_8          float64
 26   loc_og_t2m_mou_6          float64
 27   loc_og_t2m_mou_7          float64
 28   loc_og_t2m_mou_8          float64
 29   loc_og_t2f_mou_6          float64
 30   loc_og_t2f_mou_7          float64
 31   loc_og_t2f_mou_8          float64
 32   loc_og_t2c_mou_6          float64
 33   loc_og_t2c_mou_7          float64
 34   loc_og_t2c_mou_8          float64
 35   loc_og_mou_6              float64
 36   loc_og_mou_7              float64
 37   loc_og_mou_8              float64
 38   std_og_t2t_mou_6          float64
 39   std_og_t2t_mou_7          float64
 40   std_og_t2t_mou_8          float64
 41   std_og_t2m_mou_6          float64
 42   std_og_t2m_mou_7          float64
 43   std_og_t2m_mou_8          float64
 44   std_og_t2f_mou_6          float64
 45   std_og_t2f_mou_7          float64
 46   std_og_t2f_mou_8          float64
 47   std_og_t2c_mou_6          float64
 48   std_og_t2c_mou_7          float64
 49   std_og_t2c_mou_8          float64
 50   std_og_mou_6              float64
 51   std_og_mou_7              float64
 52   std_og_mou_8              float64
 53   isd_og_mou_6              float64
 54   isd_og_mou_7              float64
 55   isd_og_mou_8              float64
 56   spl_og_mou_6              float64
 57   spl_og_mou_7              float64
 58   spl_og_mou_8              float64
 59   og_others_6               float64
 60   og_others_7               float64
 61   og_others_8               float64
 62   total_og_mou_6            float64
 63   total_og_mou_7            float64
 64   total_og_mou_8            float64
 65   loc_ic_t2t_mou_6          float64
 66   loc_ic_t2t_mou_7          float64
 67   loc_ic_t2t_mou_8          float64
 68   loc_ic_t2m_mou_6          float64
 69   loc_ic_t2m_mou_7          float64
 70   loc_ic_t2m_mou_8          float64
 71   loc_ic_t2f_mou_6          float64
 72   loc_ic_t2f_mou_7          float64
 73   loc_ic_t2f_mou_8          float64
 74   loc_ic_mou_6              float64
 75   loc_ic_mou_7              float64
 76   loc_ic_mou_8              float64
 77   std_ic_t2t_mou_6          float64
 78   std_ic_t2t_mou_7          float64
 79   std_ic_t2t_mou_8          float64
 80   std_ic_t2m_mou_6          float64
 81   std_ic_t2m_mou_7          float64
 82   std_ic_t2m_mou_8          float64
 83   std_ic_t2f_mou_6          float64
 84   std_ic_t2f_mou_7          float64
 85   std_ic_t2f_mou_8          float64
 86   std_ic_t2o_mou_6          float64
 87   std_ic_t2o_mou_7          float64
 88   std_ic_t2o_mou_8          float64
 89   std_ic_mou_6              float64
 90   std_ic_mou_7              float64
 91   std_ic_mou_8              float64
 92   total_ic_mou_6            float64
 93   total_ic_mou_7            float64
 94   total_ic_mou_8            float64
 95   spl_ic_mou_6              float64
 96   spl_ic_mou_7              float64
 97   spl_ic_mou_8              float64
 98   isd_ic_mou_6              float64
 99   isd_ic_mou_7              float64
 100  isd_ic_mou_8              float64
 101  ic_others_6               float64
 102  ic_others_7               float64
 103  ic_others_8               float64
 104  total_rech_num_6          int64
 105  total_rech_num_7          int64
 106  total_rech_num_8          int64
 107  total_rech_amt_6          int64
 108  total_rech_amt_7          int64
 109  total_rech_amt_8          int64
 110  max_rech_amt_6            int64
 111  max_rech_amt_7            int64
 112  max_rech_amt_8            int64
 113  date_of_last_rech_6       object
 114  date_of_last_rech_7       object
 115  date_of_last_rech_8       object
 116  last_day_rch_amt_6        int64
 117  last_day_rch_amt_7        int64
 118  last_day_rch_amt_8        int64
 119  date_of_last_rech_data_6  object
 120  date_of_last_rech_data_7  object
 121  date_of_last_rech_data_8  object
 122  total_rech_data_6         float64
 123  total_rech_data_7         float64
 124  total_rech_data_8         float64
 125  max_rech_data_6           float64
 126  max_rech_data_7           float64
 127  max_rech_data_8           float64
 128  count_rech_2g_6           float64
 129  count_rech_2g_7           float64
 130  count_rech_2g_8           float64
 131  count_rech_3g_6           float64
 132  count_rech_3g_7           float64
 133  count_rech_3g_8           float64
 134  av_rech_amt_data_6        float64
 135  av_rech_amt_data_7        float64
 136  av_rech_amt_data_8        float64
 137  vol_2g_mb_6               float64
 138  vol_2g_mb_7               float64
 139  vol_2g_mb_8               float64
 140  vol_3g_mb_6               float64
 141  vol_3g_mb_7               float64
 142  vol_3g_mb_8               float64
 143  arpu_3g_6                 float64
 144  arpu_3g_7                 float64
 145  arpu_3g_8                 float64
 146  arpu_2g_6                 float64
 147  arpu_2g_7                 float64
 148  arpu_2g_8                 float64
 149  night_pck_user_6          float64
 150  night_pck_user_7          float64
 151  night_pck_user_8          float64
 152  monthly_2g_6              int64
 153  monthly_2g_7              int64
 154  monthly_2g_8              int64
 155  sachet_2g_6               int64
 156  sachet_2g_7               int64
 157  sachet_2g_8               int64
 158  monthly_3g_6              int64
 159  monthly_3g_7              int64
 160  monthly_3g_8              int64
 161  sachet_3g_6               int64
 162  sachet_3g_7               int64
 163  sachet_3g_8               int64
 164  fb_user_6                 float64
 165  fb_user_7                 float64
 166  fb_user_8                 float64
 167  aon                       int64
 168  aug_vbc_3g                float64
 169  jul_vbc_3g                float64
 170  jun_vbc_3g                float64
 171  churn_probability         int64
dtypes: float64(135), int64(28), object(9)
memory usage: 91.9+ MB
None

In [8]:
print('Test Data Details')
print(df_test_unseen.shape)
print(df_test_unseen.info())

Test Data Details
(30000, 171)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Columns: 171 entries, id to jun_vbc_3g
dtypes: float64(135), int64(27), object(9)
memory usage: 39.1+ MB
None

In [9]:
# Statistical description of Data
df_train.describe(include='all', percentiles=[0.05,0.25,0.5,0.75,0.95])

,id,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,churn_probability
count,69999.000000,69999.0,69297.0,69297.0,69297.0,69999,69600,69266,69999.000000,69999.000000,69999.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.0,67312.0,66296.0,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,69999.000000,69999.000000,69999.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.0,67312.0,66296.0,67231.000000,67312.000000,66296.000000,69999.000000,69999.000000,69999.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,67231.000000,67312.000000,66296.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,68898,68765,67538,69999.000000,69999.000000,69999.000000,17568,17865,18417,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,17568.000000,17865.000000,18417.000000,69999.000000,69999.000000,69999.000000,69999.00000,69999.000000
unique,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,31,31,NaN,NaN,NaN,30,31,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,6/30/2014,7/31/2014,8/31/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6/30/2014,7/31/2014,8/31/2014,NaN,NaN,NaN,6/30/2014,7/31/2014,8/31/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,69999,69600,69266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11880,12206,10324,NaN,NaN,NaN,1317,1282,1388,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,34999.000000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,283.134365,278.185912,278.858826,133.153275,133.894438,132.978257,198.874771,197.153383,196.543577,9.765435,7.014568,7.004892,14.186457,9.842191,9.771783,46.904854,46.166503,45.686109,93.238231,90.799240,91.121447,3.743179,3.777031,3.661652,1.126025,1.361052,1.420840,143.893585,140.750120,140.476486,80.619382,83.775851,83.471486,88.152110,91.538615,90.586999,1.126377,1.084062,1.057739,0.0,0.0,0.0,169.900601,176.401217,175.118852,0.845763,0.811100,0.841648,3.958619,4.976783,5.045027,0.462581,0.024425,0.033059,306.451436,310.572674,304.513065,48.043255,47.882736,47.256388,107.152439,106.489856,108.154731,12.050672,12.563665,11.716763,167.255126,166.945103,167.136761,9.476958,9.873468,9.910217,20.734858,21.685359,21.089042,2.146273,2.199395,2.075179,0.0,0.0,0.0,32.360632,33.760809,33.077030,199.710640,201.878029,198.486034,0.061932,0.033371,0.040392,7.394167,8.171162,8.348424,0.854063,1.019680,0.963214,7.566522,7.706667,7.224932,328.139788,322.376363,323.846355,104.569265,104.137573,107.540351,NaN,NaN,NaN,63.426949,59.294218,62.489478,NaN,NaN,NaN,2.467612,2.679989,2.652441,126.500000,126.402071,125.374925,1.865323,2.056311,2.016018,0.602288,0.623678,0.636423,192.831096,201.455940,196.815792,51.773924,51.240204,50.127506,122.171882,128.934444,135.486541,90.069931,89.115767,90.618564,86.863900,85.846074,86.348404,0.025273,0.024069,0.021013,0.079287,0.083401,0.080930,0.388863,0.441406,0.449492,0.075815,0.077730,0.081958,0.075344,0.081444,0.085487,0.916325,0.909544,0.890319,1220.639709,68.108597,65.935830,60.07674,0.101887
std,20207.115084,0.0,0.0,0.0,0.0,NaN,NaN,NaN,334.213918,344.366927,351.924315,299.963093,311.277193,311.896596,316.818355,322.482226,324.089234,57.374429,55.960985,53.408135,73.469261,58.511894,64.618388,150.971758,154.739002,153.716880,162.046699,153.852597,152.997805,13.319542,13.568110,13.009193,5.741811,7.914113,6.542202,252.034597,246.313148,245.342359,255.098355,266.693254,267.021929,255.771554,267.532089,270.032002,8.136645,8.325206,7.696853,0.0,0.0,0.0,392.046600,409.299501,410.697098,29.747486,29.220073,29.563367,15.854529,22.229842,17.708507,4.768437,1.716430,2.232547,465.502866,479.131770,477.936832,140.499757,147.761124,141.249368,168.455999,165.452459,166.223461,39.416076,43.495179,38.606895,252.576231,254.688718,249.288410,51.664472,56.137824,54.248186,80.294236,87.314510,81.534344,16.522232,16.171533,15.865403,0.0,0.0,0.0,104.381082,114.142230,108.469864,290.114823,296.771338,288.336731,0.164823,0.137322,0.148417,60.951165,63.604165,63.097570,12.149144,13.225373,11.697686,7.041452,7.050614,7.195597,404.211068,411.070120,426.181405,121.407701,120.782543,124.396750,NaN,NaN,NaN,97.954876,95.429492,101.996729,NaN,NaN,NaN,2.794610,3.073472,3.101265,109.352573,109.459266,109.648799,2.566377,2.799916,2.728246,1.279297,1.401230,1.457058,190.623115,198.346141,192.280532,212.513909,211.114667,213.101403,554.869965,554.096072,568.310234,193.600413,195.826990,189.907986,171.321203,178.067280,170.297094,0.156958,0.153269,0.143432,0.294719,0.304802,0.299254,1.494206,1.651012,1.632450,0.358905,0.383189,0.381821,0.573003,0.634547,0.680035,0.276907,0.286842,0.312501,952.426321,269.328659,267.899034,257.22681,0.302502
min,0.000000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,-2258.709000,-1289.715000,-945.808000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-20.380000,-26.040000,-24.490000,-35.830000,-13.090000,-55.830000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,180.000000,0.000000,0.000000,0.00000,0.000000
5%,3499.900000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,1.500000,0.919000,0.000000,0.000000,0.000000,0.000000,0.810000,0.630000,0.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.200000,0.287500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,17.000000,17.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,23.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,0.000000,0.000000,0.00000,0.000000
25%,17499.500000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,93.581000,86.714000,84.095000,7.410000,6.675000,6.410000,34.860000,32.240000,31.575000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.660000,1.650000,1.610000,9.920000,10.090000,9.830000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,17.235000,17.590000,17.237500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.780000,42.910000,38.710000,3.030000,3.260000,3.280000,17.390000,18.610000,18.940000,0.000000,0.000000,0.000000,30.630000,32.710000,32.810000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.030000,38.640000,41.340000,38.290000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,3.000000,110.000000,100.000000,90.000000,30.000000,30.000000,30.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,25.000000,25.000000,25.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,82.000000,92.000000,84.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,468.000000,0.000000,0.000000,0.00000,0.000000
50%,34999.000000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,197.484000,191.588000,192.234000,34.110000,32.280000,32.100000,96.480000,91.885000,91.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.910000,11.580000,11.740000,41.030000,40.170000,40.350000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,65.190000,63.430000,63.520000,0.000000,0.000000,0.000000,3.980000,3.710000,3.300000,0.000000,0.000000,0.000000,0.0,0.0,0.0,11.730000,11.260000,10.505000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,145.280000,141.230000,138.360000,15.740000,15.830000,16.040000,56.460000,56.930000,58.210000,0.880000,0.910000,0.930000,92.430000,92.510000,93.890000,0.000000,0.000000,0.000000,2.040000,2.060000,2.030000,0.000000,0.000000,0.000000,0.0,0.0,0.0,5.910000,5.980000,5.830000,114.780000,116.330000,114.610000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,5.000000,229.000000,220.000000,225.000000,110.000000,110.000000,98.000000,NaN,NaN,NaN,30.000000,30.000000,30.000000,NaN,NaN,NaN,1.000000,2.000000,1.000000,145.000000,145.000000,145.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,154.000000,154.000000,154.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.520000,0.420000,0.840000,11.300000,8.800000,9.090000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,868.000000,0.000000,0.000000,0.00000,0.000000
75%,52498.500000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,370.791000,365.369500,369.909000,119.390000,115.837500,115.060000,232.990000,227.630000,229.345000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,40.740000,39.760000,39.895000,110.430000,107.540000,109.245000,2.060000,2.080000,2.030000,0.000000,0.000000,0.000000,167.880000,163.932500,165.615000,31.020000,31.300000,30.760000,53.745000,54.640000,52.660000,0.000000,0.000000,0.000000,0.0,0.0,0.0,146.335000,151.645000,149.015000,0.000000,0.000000,0.000000,2.400000,3.660000,4.002500,0.000000,0.000000,0.000000,374.305000,380.045000,370.895000,46.980000,45.690000,46.280000,132.020000,131.010000,134.380000,8.140000,8.230000,8.090000,208.325000,205.530000,208.060000,4.060000,4.180000,4.052500,14.960000,15.830000,15.310000,0.000000,0.000000,0.000000,0.0,0.0,0.0,26.780000,28.160000,27.615000,251.070000,249.470000,249.710000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,10.000000,9.000000,438.000000,430.000000,436.000000,120.000000,128.000000,144.000000,NaN,NaN,NaN,110.000000,110.000000,130.000000,NaN,NaN,NaN,3.000000,3.000000,3.000000,177.000000,177.000000,179.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,252.000000,252.000000,252.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,122.070000,120.860000,122.070000,122.070000,122.070000,122.070000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1813.000000,0.000000,0.000000,0.00000,0.000000
95%,66498.100000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,832.022700,823.236700,828.464700,617.185000,628.437500,620.240000,735.985000,747.558000,738.017500,41.350000,23.199000,23.990000,69.455000,42.599000,42.110000,176.635000,174.299000,174.630000,355.220000,348.440000,347.700000,18.750000,19.019000,18.280000,6.360000,7.354500,7.852500,538.985000,530.052500,528.757500,465.765000,496.777500,491.360000,462.825000,486.712500,486.945000,4.310000,3.880000,3.900000,0.0,0.0,0.0,888.810000,924.753000,921.027500,0.000000,0.000000,0.000000,19.560000,23.380000,23.832500,2.710000,0.000000,0.000000,1171.188000,1193.257000,1174.552000,174.410000,173.534500,171.177500,372.260000,365.808000,371.767500,57.060000,58.884500,55.617500,568.035000,562.325500,568.242500,40.900000,42.149000,42.250000,86.815000,90.160000,88.545000,8.480000,8.550000,8.310000,0.0,0.0,0.0,132.820000,138.566000,136.515000,668.240000,676.904000,665.435000,0.410000,0.240000,0.310000,24.375000,28.140000,29.980000,2.110000,2.619000,2.430000,20.000000,21.000000,20.000000,998.000000,986.100000,988.000000,252.000000,252.000000,252.000000,NaN,NaN,NaN,200.000000,200.000000,225.000000,NaN,NaN,NaN,8.000000,9.000000,8.000000,252.000000,252.000000,252.000000,7.000000,8.000000,8.000000,2.000000,2.000000,2.000000,504.000000,504.000000,504.000000,327.241000,318.672000,302.284000,831.189000,866.464000,899.073000,424.806500,427.222000,424.498000,420.826000,423.174000,411.958000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3108.000000,464.277000,446.353000,400.13400,1.000000

In [10]:
df_test_unseen.describe(include='all',percentiles=[0.05,0.25,0.5,0.75,0.95])

,id,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g
count,30000.000000,30000.0,29684.0,29684.0,29684.0,30000,29798,29633,30000.000000,30000.000000,30000.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.0,28828.0,28325.0,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,30000.000000,30000.000000,30000.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.0,28828.0,28325.0,28831.000000,28828.000000,28325.000000,30000.000000,30000.000000,30000.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,28831.000000,28828.000000,28325.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,29494,29467,28839,30000.000000,30000.000000,30000.000000,7585,7706,7922,7585.000000,7706.000000,7922.000000,7585.000000,7706.000000,7922.000000,7585.000000,7706.000000,7922.000000,7585.000000,7706.000000,7922.000000,7585.000000,7706.000000,7922.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.00000,30000.000000,7585.000000,7706.000000,7922.000000,7585.000000,7706.000000,7922.000000,7585.000000,7706.000000,7922.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,7585.000000,7706.000000,7922.000000,30000.000000,30000.000000,30000.000000,30000.000000
unique,NaN,NaN,NaN,NaN,NaN,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30,31,31,NaN,NaN,NaN,30,31,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,6/30/2014,7/31/2014,8/31/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6/30/2014,7/31/2014,8/31/2014,NaN,NaN,NaN,6/30/2014,7/31/2014,8/31/2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,30000,29798,29633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5080,5082,4382,NaN,NaN,NaN,571,531,610,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,84998.500000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,282.644348,279.355021,279.845167,130.629693,133.148632,133.111348,195.745473,196.792375,196.647889,10.380431,7.465889,7.967267,13.269785,9.763957,10.440251,47.557601,47.188688,46.359887,93.584273,92.793180,93.238288,3.769281,3.830238,3.716231,1.116132,1.385891,1.464202,144.918443,143.819463,143.321709,77.988809,82.187570,82.840749,85.311712,89.089166,88.086236,1.135152,1.187272,1.091321,0.0,0.0,0.0,164.438342,172.466703,172.020983,0.687545,0.695952,0.673280,3.819317,4.981770,5.074228,0.434514,0.043803,0.034106,302.058108,309.434356,303.201238,47.640461,48.242191,47.105979,108.229345,108.593000,109.176219,12.162732,12.683831,11.833917,168.041232,169.527815,168.124943,9.806934,10.335148,9.822375,20.692815,21.588831,21.403619,2.180007,2.257851,2.107999,0.0,0.0,0.0,32.682316,34.184426,33.336607,201.108615,205.128083,199.368522,0.060682,0.034085,0.040291,7.615543,8.717343,8.661023,0.856037,0.997268,0.988557,7.540800,7.685667,7.184867,326.055900,324.331700,324.882233,104.796667,106.186967,108.166533,NaN,NaN,NaN,62.524633,59.599500,62.996933,NaN,NaN,NaN,2.454977,2.634960,2.650972,126.146473,127.488451,126.513254,1.863151,2.017778,2.016915,0.591826,0.617181,0.634057,192.068004,199.880903,199.178710,52.210692,51.205981,50.269665,119.586364,129.13912,135.233704,88.362531,90.006250,92.464772,85.318916,86.072967,87.183175,0.024654,0.020633,0.020449,0.080467,0.082800,0.081167,0.390600,0.435500,0.451433,0.076167,0.080567,0.085233,0.073467,0.077967,0.082200,0.909954,0.906956,0.891946,1218.023200,68.314097,68.946576,59.891621
std,8660.398374,0.0,0.0,0.0,0.0,NaN,NaN,NaN,314.560212,323.205370,326.437029,290.677420,302.921820,301.951806,316.923836,333.628481,334.277643,99.973352,103.337675,94.622596,66.475975,58.325466,64.933372,150.588656,156.664295,145.087354,164.481651,165.674188,164.516683,16.156500,15.772920,13.864608,4.695667,6.559241,7.316747,251.092969,254.278712,247.240694,246.248819,256.339646,261.860321,255.252441,273.537846,275.751699,7.619692,9.207658,8.375128,0.0,0.0,0.0,384.991155,408.036124,413.814560,12.179579,13.874719,11.582123,12.536781,16.427132,18.193925,1.922616,2.950457,2.523530,458.514486,482.130305,478.653833,139.696271,141.099955,127.364151,179.081640,178.346438,177.647914,41.782876,41.744180,40.313428,257.700805,259.830482,251.745391,60.090285,60.282046,56.958371,81.947033,84.642031,88.511232,16.433571,17.095798,15.688503,0.0,0.0,0.0,110.593850,112.729933,113.913175,295.209040,301.252400,291.608879,0.151429,0.191947,0.140695,56.756434,68.844483,65.457864,11.490315,11.278967,16.409030,7.163973,7.116522,7.222790,383.187192,401.136032,393.132804,118.746309,132.835730,132.566216,NaN,NaN,NaN,95.944951,97.040925,109.904928,NaN,NaN,NaN,2.776552,2.932158,3.013204,106.428898,110.474812,108.948608,2.579382,2.693674,2.701347,1.263132,1.378931,1.339962,197.264397,193.146529,189.006928,215.312764,215.051169,210.582741,518.620250,510.89113,535.877419,192.025613,196.060312,184.108675,176.078483,172.415705,163.393576,0.155078,0.142162,0.141541,0.295851,0.303448,0.300303,1.504584,1.601226,1.625176,0.373591,0.396503,0.392140,0.557327,0.613596,0.611546,0.286267,0.290513,0.310468,960.109844,263.460641,278.749349,246.098292
min,69999.000000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,-185.043000,-2014.045000,-146.859000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.500000,0.500000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,-30.820000,-9.260000,-12.040000,-19.790000,-15.480000,-20.490000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,180.000000,0.000000,0.000000,0.000000
5%,71498.950000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,1.247500,0.550000,0.000000,0.000000,0.000000,0.000000,0.670000,0.550000,0.450000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.050000,0.210000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,17.000000,17.000000,17.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,23.000000,23.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,228.000000,0.000000,0.000000,0.000000
25%,77498.750000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,92.907500,87.504750,84.180500,7.280000,6.660000,6.540000,34.385000,32.110000,31.740000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.650000,1.580000,1.580000,9.770000,9.890000,9.740000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,16.835000,17.237500,16.790000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,44.610000,43.325000,38.137500,2.910000,3.160000,3.260000,17.090000,18.530000,18.890000,0.000000,0.000000,0.000000,29.825000,31.930000,32.610000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.010000,38.137500,40.860000,38.340000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,3.000000,3.000000,104.000000,100.000000,90.000000,30.000000,30.000000,30.000000,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,25.000000,25.000000,25.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,82.000000,92.000000,91.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,466.000000,0.000000,0.000000,0.000000
50%,84998.500000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,198.227500,191.775000,191.690500,34.760000,32.550000,33.060000,95.830000,91.435000,92.810000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,11.930000,11.680000,11.690000,41.010000,41.060000,40.440000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,64.890000,64.260000,64.090000,0.000000,0.000000,0.000000,3.880000,3.390000,3.350000,0.000000,0.000000,0.000000,0.0,0.0,0.0,11.410000,10.760000,10.210000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,144.860000,142.180000,139.470000,15.580000,15.505000,15.960000,56.530000,57.385000,58.330000,0.860000,0.930000,0.930000,91.380000,92.660000,93.660000,0.000000,0.000000,0.000000,1.990000,1.980000,2.030000,0.000000,0.000000,0.000000,0.0,0.0,0.0,5.840000,5.885000,6.010000,114.655000,116.420000,114.810000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,6.000000,5.000000,230.000000,220.000000,225.000000,110.000000,110.000000,98.000000,NaN,NaN,NaN,30.000000,30.000000,30.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,145.000000,145.000000,145.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,154.000000,154.000000,154.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.410000,0.415000,0.985000,9.960000,8.865000,9.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,853.000000,0.000000,0.000000,0.000000
75%,92498.250000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,371.969250,365.250750,367.804750,117.170000,115.210000,117.730000,229.230000,224.972500,225.760000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,41.410000,40.190000,40.490000,110.330000,107.645000,108.680000,2.100000,2.130000,2.080000,0.000000,0.000000,0.000000,168.935000,165.287500,167.460000,30.200000,30.740000,30.290000,52.060000,52.532500,52.130000,0.000000,0.000000,0.000000,0.0,0.0,0.0,141.010000,148.690000,145.560000,0.000000,0.000000,0.000000,2.510000,3.800000,3.980000,0.000000,0.000000,0.000000,370.637500,376.560000,367.910000,46.635000,46.045000,46.330000,132.925000,130.880000,132.640000,8.130000,8.432500,8.160000,207.620000,206.900000,205.440000,4.060000,4.310000,4.150000,15.210000,15.560000,15.480000,0.000000,0.000000,0.000000,0.0,0.0,0.0,27.430000,28.740000,27.840000,253.357500,253.272500,247.280000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,10.000000,9.000000,436.250000,426.000000,432.000000,120.000000,128.000000,144.000000,NaN,NaN,NaN,110.000000,110.000000,130.000000,NaN,NaN,NaN,3.000000,3.000000,3.000000,154.000000,177.000000,179.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,252.000000,252.000000,252.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,121.850000,117.320000,123.195000,122.070000,122.070000,122.070000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1795.000000,0.000000,0.000000,0.000000
95%,98498.050000,109.0,0.0,0.0,0.0,NaN,NaN,NaN,821.174300,837.930800,842.554150,603.920000,618.151500,621.290000,711.925000,734.645000,726.090000,39.610000,22.962500,25.848000,68.110000,43.879500,42.080000,179.600000,180.703000,181.134000,352.420000,351.673000,360.194000,18.410000,18.836500,18.240000,6.545000,7.690000,7.910000,543.915000,544.143500,547.916000,454.430000,481.222500,481.770000,443.570000,460.284000,463.038000,4.440000,4.260000,4.108000,0.0,0.0,0.0,846.220000,890.632000,887.872000,0.010000,0.000000,0.000000,19.085000,23.736500,24.026000,2.630000,0.000000,0.000000,1141.805000,1177.909500,1165.539000,175.580000,178.379500,175.050000,372.720000,374.399500,374.000000,57.220000,59.903000,54.610000,577.295000,577.155500,572.584000,42.670000,44.490000,41.780000,87.660000,89.930000,90.120000,8.460000,8.736500,8.990000,0.0,0.0,0.0,134.945000,140.187500,134.978000,681.596500,693.216000,675.310000,0.410000,0.246500,0.310000,26.570000,30.986000,29.770000,2.030000,2.710000,2.490000,20.000000,21.000000,21.000000,986.000000,1000.000000,1000.000000,252.000000,252.000000,252.000000,NaN,NaN,NaN,200.000000,200.000000,229.000000,NaN,NaN,NaN,8.000000,8.000000,9.000000,252.000000,252.000000,252.000000,7.000000,8.000000,8.000000,2.000000,2.000000,2.000000,504.000000,504.000000,504.000000,325.914500,320.834500,312.641000,821.114500,878.30350,906.133000,431.312000,429.832500,433.862500,424.340000,424.340000,424.340000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,2.000000,3.000000,3.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3135.000000,467.705500,458.543000,400.499500

#### **Observations:**
* Data has Null values and outliers
* Data has some columns with 0 variance, i.e. all same values

In [11]:
df_train.id.nunique()

69999

In [12]:
df_train.circle_id.nunique()

1

#### **Observations:**
* ID Column has incremental values
* Circle Id has 0 variance

In [13]:
#Checking emptry rows in training dataset
empty_rows = df_train.isnull().all(axis=1).sum()
print(f'No. Empty Rows: {empty_rows}')

No. Empty Rows: 0

In [14]:
#Checking empty columns in training dataset
empty_columns = df_train.isnull().all(axis=0).sum()
print(f'No. Empty Columns: {empty_columns}')

No. Empty Columns: 0

#### **Observations:**
* Data has no empty rows and columns

In [15]:
# Printing Value counts of all columns and saving the columns with only 1 value in a list

def single_val_cols(data=df_train,verbose=False, value=False):

#     @params:
#            data: Dataframe that needs to be checked; Default: df
#            verbose: Set as True if you want info regarding value counts of each column; Default: False
#     @Return:
#            Returns a list of columns which have 0 variance

    single_val = []
    for col in data.columns :
        val_count = data[col].value_counts()
        if len(val_count) == 1:
            single_val.append(col)
        # Printing the columns and value counts
        if(verbose):
            print("Column Name:",col)
            print("Value Count:",len(val_count))
            if(not value):
                print("====================================")
        if(value):
            if(not verbose):
                print("Column Name:",col) 
            print("Unique Values:", data[col].unique())
            print("====================================")
    print("Columns with 0 Variance:")
    print(single_val)
    return single_val

single_val = single_val_cols(data=df_train,verbose=False)

Columns with 0 Variance:
['circle_id', 'loc_og_t2o_mou', 'std_og_t2o_mou', 'loc_ic_t2o_mou', 'last_date_of_month_6', 'last_date_of_month_7', 'last_date_of_month_8', 'std_og_t2c_mou_6', 'std_og_t2c_mou_7', 'std_og_t2c_mou_8', 'std_ic_t2o_mou_6', 'std_ic_t2o_mou_7', 'std_ic_t2o_mou_8']

In [16]:
# Checking for null/NaN values

def get_missing_info(data=df_train, limit=0, verbose=False) :
    # @Params:
    #        data: Dataframe to be checked; Default=df
    #        limit: Threshold for Percentage of Null values; Default=0
    #        verbose: Set as True if you want to print the entire table of features above the threashold limit
    # @Return: A dataframe with info of missing values
    
    percent_missing  = data.isnull().sum() * 100 / len(data)
    missing_value_df = pd.DataFrame({'column_name': data.columns,
                                     'percent_missing': percent_missing})
    # Sorting in descending order of perc missing
    missing_value_df.sort_values('percent_missing', inplace=True,ascending= False)
    missing_value_df.reset_index(drop=True, inplace=True)
    if (limit != 0) :
        print("No of columns with more than/equal to",limit,"% null values: ",len(missing_value_df[missing_value_df.percent_missing >= limit]))
    if(verbose):
        print("Columns with more than/equal to",limit,"% null values:")
        print(missing_value_df[missing_value_df.percent_missing >= limit])
    return missing_value_df
missing_info = get_missing_info(data=df_train,limit=30, verbose=True)

No of columns with more than/equal to 30 % null values:  30
Columns with more than/equal to 30 % null values:
                 column_name  percent_missing
0                  arpu_3g_6        74.902499
1            count_rech_2g_6        74.902499
2           night_pck_user_6        74.902499
3                  arpu_2g_6        74.902499
4   date_of_last_rech_data_6        74.902499
5          total_rech_data_6        74.902499
6         av_rech_amt_data_6        74.902499
7            max_rech_data_6        74.902499
8            count_rech_3g_6        74.902499
9                  fb_user_6        74.902499
10          night_pck_user_7        74.478207
11  date_of_last_rech_data_7        74.478207
12         total_rech_data_7        74.478207
13           max_rech_data_7        74.478207
14                 fb_user_7        74.478207
15           count_rech_2g_7        74.478207
16           count_rech_3g_7        74.478207
17                 arpu_3g_7        74.478207
18        av_rech_amt_data_7        74.478207
19                 arpu_2g_7        74.478207
20           count_rech_2g_8        73.689624
21        av_rech_amt_data_8        73.689624
22          night_pck_user_8        73.689624
23           max_rech_data_8        73.689624
24         total_rech_data_8        73.689624
25                 arpu_2g_8        73.689624
26                 arpu_3g_8        73.689624
27  date_of_last_rech_data_8        73.689624
28                 fb_user_8        73.689624
29           count_rech_3g_8        73.689624

####  **Data Cleaning and Manipulation**

In [17]:
# Creating a copy of 'df_train' to clean & transform data
df_train_cleaned = df_train
df_test_unseen_cleaned = df_test_unseen

In [18]:
#As features count is too high, let's try to seperate them w.r.t data understanding.
id_cols = ['id', 'circle_id']

date_cols = ['last_date_of_month_6',
             'last_date_of_month_7',
             'last_date_of_month_8',
             'date_of_last_rech_6',
             'date_of_last_rech_7',
             'date_of_last_rech_8',
             'date_of_last_rech_data_6',
             'date_of_last_rech_data_7',
             'date_of_last_rech_data_8'
            ]

cat_cols =  ['night_pck_user_6',
             'night_pck_user_7',
             'night_pck_user_8',
             'fb_user_6',
             'fb_user_7',
             'fb_user_8'
            ]
target_cols = ['churn_probability']

In [19]:
num_cols = [column for column in df_train.select_dtypes(include=['int64','float64']) if column not in (id_cols + cat_cols + target_cols)]

# Print the number of columns in each list
print("ID columns: ", len(id_cols))
print("DATE columns: ", len(date_cols)) 
print("NUM cols: ", len(num_cols))
print("CATEGORY cols: ", len(cat_cols))
print("TARGET cols: ", len(target_cols))
print("TOTAL SUM: ", len(id_cols) + len(date_cols) + len(num_cols) + len(cat_cols) + len(target_cols))
print("TOTAL Columns: ", df_train.shape[1])

# Validate if we have missed any column or not
print("Checking segregation is done correctly : ",len(id_cols) + len(date_cols) + len(num_cols) + len(cat_cols) + len(target_cols) == df_train.shape[1])

ID columns:  2
DATE columns:  9
NUM cols:  154
CATEGORY cols:  6
TARGET cols:  1
TOTAL SUM:  172
TOTAL Columns:  172
Checking segregation is done correctly :  True

In [20]:
# some recharge data columns have minimum value of 1 while some don't
rech_cols = ['total_rech_data_6', 'total_rech_data_7', 'total_rech_data_8',
                 'count_rech_2g_6', 'count_rech_2g_7', 'count_rech_2g_8',
                 'count_rech_3g_6', 'count_rech_3g_7', 'count_rech_3g_8',
                 'max_rech_data_6', 'max_rech_data_7', 'max_rech_data_8',
                 'av_rech_amt_data_6', 'av_rech_amt_data_7', 'av_rech_amt_data_8'
                 ]

df_train_cleaned[rech_cols].describe(include='all')

,total_rech_data_6,total_rech_data_7,total_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8
count,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000,17568.000000,17865.000000,18417.000000
mean,2.467612,2.679989,2.652441,1.865323,2.056311,2.016018,0.602288,0.623678,0.636423,126.500000,126.402071,125.374925,192.831096,201.455940,196.815792
std,2.794610,3.073472,3.101265,2.566377,2.799916,2.728246,1.279297,1.401230,1.457058,109.352573,109.459266,109.648799,190.623115,198.346141,192.280532
min,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,25.000000,25.000000,25.000000,82.000000,92.000000,84.000000
50%,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,145.000000,145.000000,145.000000,154.000000,154.000000,154.000000
75%,3.000000,3.000000,3.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,177.000000,177.000000,179.000000,252.000000,252.000000,252.000000
max,61.000000,54.000000,60.000000,42.000000,48.000000,44.000000,29.000000,34.000000,45.000000,1555.000000,1555.000000,1555.000000,5920.000000,4365.000000,4076.000000

In [21]:
# Recharge date and the recharge value are missing in same month, that is customer not recharged service in that particular month
df_train_cleaned.loc[df_train_cleaned.total_rech_data_6.isnull() & df_train_cleaned.date_of_last_rech_data_6.isnull(), ["total_rech_data_6", "date_of_last_rech_data_6"]].head(5)
df_train_cleaned.loc[df_train_cleaned.total_rech_data_7.isnull() & df_train_cleaned.date_of_last_rech_data_7.isnull(), ["total_rech_data_7", "date_of_last_rech_data_7"]].head(5)
df_train_cleaned.loc[df_train_cleaned.total_rech_data_8.isnull() & df_train_cleaned.date_of_last_rech_data_8.isnull(), ["total_rech_data_8", "date_of_last_rech_data_8"]].head(5)
df_train_cleaned[["total_rech_data_6", "date_of_last_rech_data_6","total_rech_data_7", "date_of_last_rech_data_7","total_rech_data_8", "date_of_last_rech_data_8"]].head()

   total_rech_data_6 date_of_last_rech_data_6
0                NaN                      NaN
1                NaN                      NaN
2                NaN                      NaN
3                NaN                      NaN
5                NaN                      NaN

   total_rech_data_7 date_of_last_rech_data_7
0                NaN                      NaN
2                NaN                      NaN
3                NaN                      NaN
5                NaN                      NaN
6                NaN                      NaN

   total_rech_data_8 date_of_last_rech_data_8
0                NaN                      NaN
1                NaN                      NaN
2                NaN                      NaN
3                NaN                      NaN
5                NaN                      NaN

,total_rech_data_6,date_of_last_rech_data_6,total_rech_data_7,date_of_last_rech_data_7,total_rech_data_8,date_of_last_rech_data_8
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,1.0,7/8/2014,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,7.0,6/25/2014,7.0,7/23/2014,6.0,8/20/2014

#### **Observations:**
* Recharge is not done in some months, thus there is no record available; Hence, we can replace null values with 0

In [22]:
# List of recharge columns where we will impute missing values with 0s
impute_0s = ['total_rech_data_6', 'total_rech_data_7', 'total_rech_data_8', 'av_rech_amt_data_6', 'av_rech_amt_data_7', 'av_rech_amt_data_8',
             'max_rech_data_6', 'max_rech_data_7', 'max_rech_data_8']

In [23]:
# impute missing values with 0 in both train and unseen test data
df_train_cleaned[impute_0s] = df_train_cleaned[impute_0s].fillna(0)
df_test_unseen_cleaned[impute_0s] = df_test_unseen[impute_0s].fillna(0)

In [24]:
# Verifying the recharge columns with manual imputation
print("Missing value percentage in TRAIN Recharge Columns:")
get_missing_info(data=df_train_cleaned[impute_0s])

# Verification of 0s imputation (TEST)
print("Missing value percentage in TEST Recharge Columns:")
get_missing_info(data=df_test_unseen_cleaned[impute_0s])

Missing value percentage in TRAIN Recharge Columns:

          column_name  percent_missing
0   total_rech_data_6              0.0
1   total_rech_data_7              0.0
2   total_rech_data_8              0.0
3  av_rech_amt_data_6              0.0
4  av_rech_amt_data_7              0.0
5  av_rech_amt_data_8              0.0
6     max_rech_data_6              0.0
7     max_rech_data_7              0.0
8     max_rech_data_8              0.0

Missing value percentage in TEST Recharge Columns:

          column_name  percent_missing
0   total_rech_data_6              0.0
1   total_rech_data_7              0.0
2   total_rech_data_8              0.0
3  av_rech_amt_data_6              0.0
4  av_rech_amt_data_7              0.0
5  av_rech_amt_data_8              0.0
6     max_rech_data_6              0.0
7     max_rech_data_7              0.0
8     max_rech_data_8              0.0

In [25]:
# Lets see rech columns stats for train dataset
df_train_cleaned[impute_0s].describe(include='all')

,total_rech_data_6,total_rech_data_7,total_rech_data_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8
count,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000,69999.000000
mean,0.619309,0.683981,0.697867,48.395787,51.415168,51.782975,31.748339,32.260075,32.986614
std,1.762010,1.943193,1.973434,126.923180,133.246541,131.291162,77.519536,78.069163,78.808337
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,8.000000,17.000000,23.000000,8.000000,14.000000,17.000000
max,61.000000,54.000000,60.000000,5920.000000,4365.000000,4076.000000,1555.000000,1555.000000,1555.000000

In [26]:
# Lets see rech columns stats for test dataset
df_test_unseen_cleaned[impute_0s].describe(include='all')

,total_rech_data_6,total_rech_data_7,total_rech_data_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,0.620700,0.676833,0.700033,48.561194,51.342741,52.596458,31.894033,32.747533,33.407933
std,1.757138,1.879782,1.939874,129.640618,131.180208,130.929389,76.614487,78.976636,79.023333
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,14.000000,17.000000,23.000000,14.000000,17.000000,17.000000
max,55.000000,44.000000,57.000000,7546.000000,3765.000000,2520.000000,1555.000000,1555.000000,1555.000000

In [27]:
# we can drop id columns and date columns as there is not much significance
df_train_cleaned = df_train_cleaned.drop(id_cols + date_cols, axis=1)
df_train_cleaned.shape

(69999, 161)

In [28]:
# doing the same for test data
df_test_unseen_cleaned = df_test_unseen_cleaned.drop(id_cols + date_cols, axis=1)
df_test_unseen_cleaned.shape

(30000, 160)

#### **Fixing Null values for Category columns**

In [29]:
single_val_cols(data=df_train_cleaned[cat_cols], verbose=True, value=True)

Column Name: night_pck_user_6
Value Count: 2
Unique Values: [nan  0.  1.]
====================================
Column Name: night_pck_user_7
Value Count: 2
Unique Values: [nan  0.  1.]
====================================
Column Name: night_pck_user_8
Value Count: 2
Unique Values: [nan  0.  1.]
====================================
Column Name: fb_user_6
Value Count: 2
Unique Values: [nan  1.  0.]
====================================
Column Name: fb_user_7
Value Count: 2
Unique Values: [nan  1.  0.]
====================================
Column Name: fb_user_8
Value Count: 2
Unique Values: [nan  1.  0.]
====================================
Columns with 0 Variance:
[]

[]

#### **Observations:**
* We can see that the cat columns have Nan/Null values, Let's replace them with -1 to indicate that these are not relevant

In [30]:
df_train_cleaned[cat_cols] = df_train_cleaned[cat_cols].fillna(-1)
df_test_unseen_cleaned[cat_cols] = df_test_unseen_cleaned[cat_cols].fillna(-1)

In [31]:
# Verifying the category columns with manual imputation
print("Missing value parcentage TRAIN:")
get_missing_info(data= df_train_cleaned[cat_cols])

print("Missing value parcentage TEST:")
get_missing_info(data= df_test_unseen_cleaned[cat_cols])

Missing value parcentage TRAIN:

        column_name  percent_missing
0  night_pck_user_6              0.0
1  night_pck_user_7              0.0
2  night_pck_user_8              0.0
3         fb_user_6              0.0
4         fb_user_7              0.0
5         fb_user_8              0.0

Missing value parcentage TEST:

        column_name  percent_missing
0  night_pck_user_6              0.0
1  night_pck_user_7              0.0
2  night_pck_user_8              0.0
3         fb_user_6              0.0
4         fb_user_7              0.0
5         fb_user_8              0.0

#### **Dropping columns with more than 70% null values**

In [32]:
missing_cols_70 = get_missing_info(data=df_train_cleaned, limit=70, verbose=False)
missing_cols_70[missing_cols_70.percent_missing >= 70]

No of columns with more than/equal to 70 % null values:  12

        column_name  percent_missing
0   count_rech_3g_6        74.902499
1         arpu_2g_6        74.902499
2   count_rech_2g_6        74.902499
3         arpu_3g_6        74.902499
4         arpu_2g_7        74.478207
5   count_rech_2g_7        74.478207
6   count_rech_3g_7        74.478207
7         arpu_3g_7        74.478207
8         arpu_3g_8        73.689624
9   count_rech_2g_8        73.689624
10  count_rech_3g_8        73.689624
11        arpu_2g_8        73.689624

In [33]:
initial_n_columns = df_train_cleaned.shape[1]

MISSING_THRESHOLD = 0.7

include_columns = list(df_train_cleaned.apply(lambda column: True if column.isnull().sum()/df_train_cleaned.shape[0] < MISSING_THRESHOLD else False))

drop_missing = pd.DataFrame({'features':df_train_cleaned.columns , 'include': include_columns})
drop_missing.loc[drop_missing.include == True,:]

               features  include
0        loc_og_t2o_mou     True
1        std_og_t2o_mou     True
2        loc_ic_t2o_mou     True
3                arpu_6     True
4                arpu_7     True
5                arpu_8     True
6           onnet_mou_6     True
7           onnet_mou_7     True
8           onnet_mou_8     True
9          offnet_mou_6     True
10         offnet_mou_7     True
11         offnet_mou_8     True
12        roam_ic_mou_6     True
13        roam_ic_mou_7     True
14        roam_ic_mou_8     True
15        roam_og_mou_6     True
16        roam_og_mou_7     True
17        roam_og_mou_8     True
18     loc_og_t2t_mou_6     True
19     loc_og_t2t_mou_7     True
20     loc_og_t2t_mou_8     True
21     loc_og_t2m_mou_6     True
22     loc_og_t2m_mou_7     True
23     loc_og_t2m_mou_8     True
24     loc_og_t2f_mou_6     True
25     loc_og_t2f_mou_7     True
26     loc_og_t2f_mou_8     True
27     loc_og_t2c_mou_6     True
28     loc_og_t2c_mou_7     True
29     loc_og_t2c_mou_8     True
30         loc_og_mou_6     True
31         loc_og_mou_7     True
32         loc_og_mou_8     True
33     std_og_t2t_mou_6     True
34     std_og_t2t_mou_7     True
35     std_og_t2t_mou_8     True
36     std_og_t2m_mou_6     True
37     std_og_t2m_mou_7     True
38     std_og_t2m_mou_8     True
39     std_og_t2f_mou_6     True
40     std_og_t2f_mou_7     True
41     std_og_t2f_mou_8     True
42     std_og_t2c_mou_6     True
43     std_og_t2c_mou_7     True
44     std_og_t2c_mou_8     True
45         std_og_mou_6     True
46         std_og_mou_7     True
47         std_og_mou_8     True
48         isd_og_mou_6     True
49         isd_og_mou_7     True
50         isd_og_mou_8     True
51         spl_og_mou_6     True
52         spl_og_mou_7     True
53         spl_og_mou_8     True
54          og_others_6     True
55          og_others_7     True
56          og_others_8     True
57       total_og_mou_6     True
58       total_og_mou_7     True
59       total_og_mou_8     True
60     loc_ic_t2t_mou_6     True
61     loc_ic_t2t_mou_7     True
62     loc_ic_t2t_mou_8     True
63     loc_ic_t2m_mou_6     True
64     loc_ic_t2m_mou_7     True
65     loc_ic_t2m_mou_8     True
66     loc_ic_t2f_mou_6     True
67     loc_ic_t2f_mou_7     True
68     loc_ic_t2f_mou_8     True
69         loc_ic_mou_6     True
70         loc_ic_mou_7     True
71         loc_ic_mou_8     True
72     std_ic_t2t_mou_6     True
73     std_ic_t2t_mou_7     True
74     std_ic_t2t_mou_8     True
75     std_ic_t2m_mou_6     True
76     std_ic_t2m_mou_7     True
77     std_ic_t2m_mou_8     True
78     std_ic_t2f_mou_6     True
79     std_ic_t2f_mou_7     True
80     std_ic_t2f_mou_8     True
81     std_ic_t2o_mou_6     True
82     std_ic_t2o_mou_7     True
83     std_ic_t2o_mou_8     True
84         std_ic_mou_6     True
85         std_ic_mou_7     True
86         std_ic_mou_8     True
87       total_ic_mou_6     True
88       total_ic_mou_7     True
89       total_ic_mou_8     True
90         spl_ic_mou_6     True
91         spl_ic_mou_7     True
92         spl_ic_mou_8     True
93         isd_ic_mou_6     True
94         isd_ic_mou_7     True
95         isd_ic_mou_8     True
96          ic_others_6     True
97          ic_others_7     True
98          ic_others_8     True
99     total_rech_num_6     True
100    total_rech_num_7     True
101    total_rech_num_8     True
102    total_rech_amt_6     True
103    total_rech_amt_7     True
104    total_rech_amt_8     True
105      max_rech_amt_6     True
106      max_rech_amt_7     True
107      max_rech_amt_8     True
108  last_day_rch_amt_6     True
109  last_day_rch_amt_7     True
110  last_day_rch_amt_8     True
111   total_rech_data_6     True
112   total_rech_data_7     True
113   total_rech_data_8     True
114     max_rech_data_6     True
115     max_rech_data_7     True
116     max_rech_data_8     True
123  av_rech_amt_data_6     True
124  av_rech_amt_data_7     True
125  av_rech_amt_data_8     True
126         vol_2g_mb_6     True
127         vol_2g_mb_7     True
128         vol_2g_mb_8     True
129         vol_3g_mb_6     True
130         vol_3g_mb_7     True
131         vol_3g_mb_8     True
138    night_pck_user_6     True
139    night_pck_user_7     True
140    night_pck_user_8     True
141        monthly_2g_6     True
142        monthly_2g_7     True
143        monthly_2g_8     True
144         sachet_2g_6     True
145         sachet_2g_7     True
146         sachet_2g_8     True
147        monthly_3g_6     True
148        monthly_3g_7     True
149        monthly_3g_8     True
150         sachet_3g_6     True
151         sachet_3g_7     True
152         sachet_3g_8     True
153           fb_user_6     True
154           fb_user_7     True
155           fb_user_8     True
156                 aon     True
157          aug_vbc_3g     True
158          jul_vbc_3g     True
159          jun_vbc_3g     True
160   churn_probability     True

In [34]:
#columns to drop
drop_missing.loc[drop_missing.include == False,:].reset_index()

    index         features  include
0     117  count_rech_2g_6    False
1     118  count_rech_2g_7    False
2     119  count_rech_2g_8    False
3     120  count_rech_3g_6    False
4     121  count_rech_3g_7    False
5     122  count_rech_3g_8    False
6     132        arpu_3g_6    False
7     133        arpu_3g_7    False
8     134        arpu_3g_8    False
9     135        arpu_2g_6    False
10    136        arpu_2g_7    False
11    137        arpu_2g_8    False

In [35]:
df_train_cleaned = df_train_cleaned.loc[:, include_columns]

In [36]:
df_test_unseen_cleaned = df_test_unseen_cleaned.loc[:, include_columns[:-1]]

In [37]:
get_missing_info(data=df_train_cleaned)
#(df_train_cleaned.isnull().sum() * 100 / len(df_train_cleaned)).sort_values(ascending = False)

            column_name  percent_missing
0      std_ic_t2t_mou_8         5.290076
1          spl_og_mou_8         5.290076
2      loc_og_t2c_mou_8         5.290076
3          loc_og_mou_8         5.290076
4      std_og_t2t_mou_8         5.290076
5      std_og_t2m_mou_8         5.290076
6      std_og_t2f_mou_8         5.290076
7      std_og_t2c_mou_8         5.290076
8          std_og_mou_8         5.290076
9          isd_og_mou_8         5.290076
10          og_others_8         5.290076
11     loc_og_t2m_mou_8         5.290076
12         spl_ic_mou_8         5.290076
13     loc_ic_t2t_mou_8         5.290076
14     loc_ic_t2m_mou_8         5.290076
15     loc_ic_t2f_mou_8         5.290076
16         loc_ic_mou_8         5.290076
17     std_ic_t2m_mou_8         5.290076
18     std_ic_t2f_mou_8         5.290076
19     std_ic_t2o_mou_8         5.290076
20     loc_og_t2f_mou_8         5.290076
21         std_ic_mou_8         5.290076
22        roam_ic_mou_8         5.290076
23        roam_og_mou_8         5.290076
24     loc_og_t2t_mou_8         5.290076
25          onnet_mou_8         5.290076
26          ic_others_8         5.290076
27         offnet_mou_8         5.290076
28         isd_ic_mou_8         5.290076
29         isd_og_mou_6         3.954342
30     std_ic_t2m_mou_6         3.954342
31        roam_ic_mou_6         3.954342
32         spl_og_mou_6         3.954342
33     loc_og_t2m_mou_6         3.954342
34         isd_ic_mou_6         3.954342
35     std_ic_t2t_mou_6         3.954342
36         std_og_mou_6         3.954342
37         offnet_mou_6         3.954342
38     loc_ic_t2t_mou_6         3.954342
39     loc_ic_t2m_mou_6         3.954342
40         loc_ic_mou_6         3.954342
41          onnet_mou_6         3.954342
42          ic_others_6         3.954342
43          og_others_6         3.954342
44     loc_ic_t2f_mou_6         3.954342
45         loc_og_mou_6         3.954342
46     std_og_t2c_mou_6         3.954342
47     loc_og_t2f_mou_6         3.954342
48        roam_og_mou_6         3.954342
49     std_ic_t2f_mou_6         3.954342
50     std_og_t2f_mou_6         3.954342
51     loc_og_t2c_mou_6         3.954342
52         std_ic_mou_6         3.954342
53     std_og_t2m_mou_6         3.954342
54         spl_ic_mou_6         3.954342
55     std_ic_t2o_mou_6         3.954342
56     std_og_t2t_mou_6         3.954342
57     loc_og_t2t_mou_6         3.954342
58         std_ic_mou_7         3.838626
59         loc_ic_mou_7         3.838626
60     loc_ic_t2f_mou_7         3.838626
61     std_ic_t2o_mou_7         3.838626
62          ic_others_7         3.838626
63         spl_ic_mou_7         3.838626
64     std_ic_t2f_mou_7         3.838626
65     std_ic_t2m_mou_7         3.838626
66     std_ic_t2t_mou_7         3.838626
67     loc_og_t2m_mou_7         3.838626
68          onnet_mou_7         3.838626
69     std_og_t2f_mou_7         3.838626
70     loc_og_t2f_mou_7         3.838626
71     loc_og_t2c_mou_7         3.838626
72     loc_og_t2t_mou_7         3.838626
73         loc_og_mou_7         3.838626
74     std_og_t2t_mou_7         3.838626
75     std_og_t2m_mou_7         3.838626
76        roam_og_mou_7         3.838626
77         std_og_mou_7         3.838626
78     loc_ic_t2m_mou_7         3.838626
79        roam_ic_mou_7         3.838626
80         isd_og_mou_7         3.838626
81         spl_og_mou_7         3.838626
82          og_others_7         3.838626
83         offnet_mou_7         3.838626
84         isd_ic_mou_7         3.838626
85     loc_ic_t2t_mou_7         3.838626
86     std_og_t2c_mou_7         3.838626
87       loc_og_t2o_mou         1.002871
88       std_og_t2o_mou         1.002871
89       loc_ic_t2o_mou         1.002871
90       total_ic_mou_7         0.000000
91          sachet_2g_8         0.000000
92          vol_2g_mb_8         0.000000
93          vol_3g_mb_6         0.000000
94          vol_3g_mb_7         0.000000
95          vol_3g_mb_8         0.000000
96     night_pck_user_6         0.000000
97     night_pck_user_7         0.000000
98     night_pck_user_8         0.000000
99         monthly_2g_6         0.000000
100        monthly_2g_7         0.000000
101        monthly_2g_8         0.000000
102         sachet_2g_6         0.000000
103         sachet_2g_7         0.000000
104        monthly_3g_7         0.000000
105        monthly_3g_6         0.000000
106         vol_2g_mb_6         0.000000
107        monthly_3g_8         0.000000
108         sachet_3g_6         0.000000
109         sachet_3g_7         0.000000
110         sachet_3g_8         0.000000
111           fb_user_6         0.000000
112           fb_user_7         0.000000
113           fb_user_8         0.000000
114                 aon         0.000000
115          aug_vbc_3g         0.000000
116          jul_vbc_3g         0.000000
117          jun_vbc_3g         0.000000
118         vol_2g_mb_7         0.000000
119  av_rech_amt_data_7         0.000000
120  av_rech_amt_data_8         0.000000
121    total_rech_amt_8         0.000000
122      total_ic_mou_6         0.000000
123      total_og_mou_8         0.000000
124      total_og_mou_7         0.000000
125      total_og_mou_6         0.000000
126              arpu_8         0.000000
127              arpu_7         0.000000
128              arpu_6         0.000000
129    total_rech_num_6         0.000000
130    total_rech_num_7         0.000000
131    total_rech_num_8         0.000000
132    total_rech_amt_6         0.000000
133    total_rech_amt_7         0.000000
134      max_rech_amt_6         0.000000
135      total_ic_mou_8         0.000000
136      max_rech_amt_7         0.000000
137      max_rech_amt_8         0.000000
138  last_day_rch_amt_6         0.000000
139  last_day_rch_amt_7         0.000000
140  last_day_rch_amt_8         0.000000
141   total_rech_data_6         0.000000
142   total_rech_data_7         0.000000
143   total_rech_data_8         0.000000
144     max_rech_data_6         0.000000
145     max_rech_data_7         0.000000
146     max_rech_data_8         0.000000
147  av_rech_amt_data_6         0.000000
148   churn_probability         0.000000

In [38]:
df_train_cleaned.shape

(69999, 149)

#### **To fix the null values we can use IterativeImputer sklearn function**

In [ ]:
ite_imputer = IterativeImputer(max_iter=1, verbose=2)
ite_imputer.fit(df_train_cleaned)

[IterativeImputer] Completing matrix with shape (69999, 149)

In [ ]:
# IterativeImputer on train dataset
df_train_cleaned_imputed = ite_imputer.transform(df_train_cleaned)
df_train_cleaned_imputed = pd.DataFrame(df_train_cleaned_imputed, columns=df_train_cleaned.columns)

In [ ]:
# IterativeImputer on test dataset
ite_imputer = IterativeImputer(max_iter=1, verbose=2)
ite_imputer.fit(df_test_unseen_cleaned)
df_test_unseen_cleaned_imputed = ite_imputer.transform(df_test_unseen_cleaned)
df_test_unseen_cleaned_imputed = pd.DataFrame(df_test_unseen_cleaned_imputed, columns=df_test_unseen_cleaned.columns)

In [ ]:
#verifying the null values for train dataset
get_missing_info(data=df_train_cleaned_imputed)

In [ ]:
#verifying the null values for test dataset
get_missing_info(data=df_test_unseen_cleaned_imputed)

#### **Finding high value Customers from given dataset using derived columns**

In [ ]:
# calculate the total data recharge amount for June, July and Aug 
# Total Recharge = number of recharges * average recharge amount
df_train_cleaned_imputed['total_data_rech_6'] = df_train_cleaned_imputed.total_rech_data_6 * df_train_cleaned_imputed.av_rech_amt_data_6
df_train_cleaned_imputed['total_data_rech_7'] = df_train_cleaned_imputed.total_rech_data_7 * df_train_cleaned_imputed.av_rech_amt_data_7
df_train_cleaned_imputed['total_data_rech_8'] = df_train_cleaned_imputed.total_rech_data_8 * df_train_cleaned_imputed.av_rech_amt_data_8

# for TEST
df_test_unseen_cleaned_imputed['total_data_rech_6'] = df_test_unseen_cleaned_imputed.total_rech_data_6 * df_test_unseen_cleaned_imputed.av_rech_amt_data_6
df_test_unseen_cleaned_imputed['total_data_rech_7'] = df_test_unseen_cleaned_imputed.total_rech_data_7 * df_test_unseen_cleaned_imputed.av_rech_amt_data_7
df_test_unseen_cleaned_imputed['total_data_rech_8'] = df_test_unseen_cleaned_imputed.total_rech_data_8 * df_test_unseen_cleaned_imputed.av_rech_amt_data_8

#### To find the Total amount we need to add recharge amount + total data recharge amount

In [ ]:
# calculate total recharge amount for June and July --> call recharge amount + data recharge amount
df_train_cleaned_imputed['amt_data_6'] = df_train_cleaned_imputed.total_rech_amt_6 + df_train_cleaned_imputed.total_data_rech_6
df_train_cleaned_imputed['amt_data_7'] = df_train_cleaned_imputed.total_rech_amt_7 + df_train_cleaned_imputed.total_data_rech_7
df_train_cleaned_imputed['amt_data_8'] = df_train_cleaned_imputed.total_rech_amt_8 + df_train_cleaned_imputed.total_data_rech_8

# for TEST
df_test_unseen_cleaned_imputed['amt_data_6'] = df_test_unseen_cleaned_imputed.total_rech_amt_6 + df_test_unseen_cleaned_imputed.total_data_rech_6
df_test_unseen_cleaned_imputed['amt_data_7'] = df_test_unseen_cleaned_imputed.total_rech_amt_7 + df_test_unseen_cleaned_imputed.total_data_rech_7
df_test_unseen_cleaned_imputed['amt_data_8'] = df_test_unseen_cleaned_imputed.total_rech_amt_8 + df_test_unseen_cleaned_imputed.total_data_rech_8

In [ ]:
# Calculating avg amount spend by customers
df_train_cleaned_imputed['av_amt_data_6_7_8'] = (df_train_cleaned_imputed.amt_data_6 + df_train_cleaned_imputed.amt_data_7 + df_train_cleaned_imputed.amt_data_8)/3

# for TEST
df_test_unseen_cleaned_imputed['av_amt_data_6_7_8'] = (df_test_unseen_cleaned_imputed.amt_data_6 + df_test_unseen_cleaned_imputed.amt_data_7 + df_test_unseen_cleaned_imputed.amt_data_8)/2

#### **Considering 70th percentile as the cutoff for High Value Customers**

In [ ]:
# look at the 70th percentile recharge amount
print("Recharge amount at 70th percentile (TRAIN): {0}".format(df_train_cleaned_imputed.av_amt_data_6_7_8.quantile(0.7)))

In [ ]:
#Since we need to focus on high-value customer, lets retain the records which have more than 70%

df_train_filtered = df_train_cleaned_imputed.loc[df_train_cleaned_imputed.av_amt_data_6_7_8 >= df_train_cleaned_imputed.av_amt_data_6_7_8.quantile(0.7), :]
df_train_filtered = df_train_filtered.reset_index(drop = True)
print(df_train_filtered.shape)

# for TEST (WE DO NOT REMOVE ROWS for TEST)
df_test_filtered = df_test_unseen_cleaned_imputed
df_test_filtered = df_test_filtered.reset_index(drop = True)
print(df_test_filtered.shape)

In [ ]:
# Delete variables created to filter high-value customers
drop_columns_high_value = ['total_data_rech_6', 'total_data_rech_7','total_data_rech_8',
                           'amt_data_6', 'amt_data_7','amt_data_8', 'av_amt_data_6_7_8']
df_train_filtered = df_train_filtered.drop(drop_columns_high_value, axis=1)
df_train_filtered.shape

In [ ]:
# Delete variables in TEST created to filter high-value customers in TRAIN
df_test_filtered = df_test_filtered.drop(drop_columns_high_value, axis=1)

#### **Observations:**
* We're left with 21001 rows after selecting the customers who have provided recharge value of more than or equal to the recharge value of the 70th percentile customer.

#### **Deriving New Features**

In [ ]:
# Calculate total incoming and outgoing minutes of usage in TRAIN
#df_train_filtered['total_calls_mou_8'] = df_train_filtered.total_ic_mou_8 + df_train_filtered.total_og_mou_8

In [ ]:
# calculate 2g and 3g data consumption
#df_train_filtered['total_internet_mb_8'] =  df_train_filtered.vol_2g_mb_8 + df_train_filtered.vol_3g_mb_8

In [ ]:
# Create "Churn Variable": those who have not used either calls or internet in the month 8 are customers who have churned
# 0 = Not churn, 1 = Churn
#df_train_filtered['churn'] = df_train_filtered.apply(lambda row: 1 if (row.total_calls_mou_8 == 0 and row.total_internet_mb_8 == 0) else 0, axis=1)

In [ ]:
# Delete derived variables just created
# df_train_filtered = df_train_filtered.drop(['total_calls_mou_8', 'total_internet_mb_8'], axis=1)

In [ ]:
#Remaning column for the ease of utilization
df_train_filtered.rename(columns = {'churn_probability':'churn'}, inplace = True)

In [ ]:
# Change data type to category
df_train_filtered.churn = df_train_filtered.churn.astype("category")

# print churn ratio
print("Churn Ratio:")
print(df_train_filtered.churn.value_counts()*100/df_train_filtered.shape[0])

In [ ]:
# Show details for columns
df_train_filtered.describe()

#### **Checking for Columns with 0 Variance**

In [ ]:
single_cols_filtered = single_val_cols(data=df_train_filtered)

In [ ]:
# Dropping columns with 0 variance
df_train_filtered = df_train_filtered.drop(columns = single_cols_filtered)
df_test_filtered = df_test_filtered.drop(columns = single_cols_filtered)

In [ ]:
# Shape of TRAIN and TEST. They should remain the same
print("TRAIN Shape: ", df_train_filtered.shape)
print("TEST Shape: ", df_test_filtered.shape)

#### **Observations:**
* Train data has additional "churn" field

#### **Univariable Analysis**

In [ ]:
df_train_filtered.head()

#### **Plot Numeric Data**

In [ ]:
print("Categorical Columns\n", cat_cols)
print("\nNumerical Columns\n", num_cols)

In [ ]:
univariate(df_train_filtered, 'arpu_6')

In [ ]:
univariate(df_train_filtered, 'arpu_7')

In [ ]:
univariate(df_train_filtered, 'arpu_8')

In [ ]:
univariate(df_train_filtered, 'onnet_mou_6')

In [ ]:
univariate(df_train_filtered, 'onnet_mou_7')

In [ ]:
univariate(df_train_filtered, 'onnet_mou_8')

In [ ]:
univariate(df_train_filtered, 'offnet_mou_6')

In [ ]:
univariate(df_train_filtered, 'offnet_mou_7')

In [ ]:
univariate(df_train_filtered, 'offnet_mou_8')

#### **Observations:**
* Variables are skewed todards left. with many outliers

#### **Plot Categorical Data**

In [ ]:
# Plotting Categorical Data with a loop
for col in cat_cols:
    # Plotting Categorical Data:
    univar_plot_byCheckingColTyp(df_train_filtered, col, 1)

Observation: We can see there data is well adjusted for category columns and for numerical columns there are outliyers which we treat them later

#### Bivariable Analysis

In [ ]:
bivariate(df_train_filtered, 'churn', 'aon')

In [ ]:
bivariate(df_train_filtered, 'spl_og_mou_8', 'churn')

In [ ]:
bivariate(df_train_filtered, 'churn', 'arpu_6')

In [ ]:
bivariate(df_train_filtered, 'churn', 'onnet_mou_6')

In [ ]:
bivariate(df_train_filtered, 'churn', 'offnet_mou_6')

In [ ]:
pd.crosstab(df_train_filtered.churn, df_train_filtered.night_pck_user_8, normalize='columns')*100

In [ ]:
pd.crosstab(df_train_filtered.churn, df_train_filtered.sachet_3g_8)

In [ ]:
#Histogram to check the co-relation
rech_df = df_train_filtered.filter(regex = 'rech')
print(rech_df.columns)
fig = plt.figure(figsize=(22, 15))
sns.heatmap(rech_df.corr(), annot = True, cmap="YlGnBu")
plt.show()

In [ ]:
rech_df = df_train_filtered.filter(regex = 'ic_mou')
print(rech_df.columns)
fig = plt.figure(figsize=(22, 15))
sns.heatmap(rech_df.corr(), annot = True, cmap="YlGnBu")
plt.show()

In [ ]:
rech_df = df_train_filtered.filter(regex = 'og_mou')
print(rech_df.columns)
fig = plt.figure(figsize=(22, 15))
sns.heatmap(rech_df.corr(), annot = True, cmap="YlGnBu")
plt.show()

#### **Observations:**
* We can clearly see that some features are highly correlated with each other

#### **Standard deviation outlier treatment**

In [ ]:
num_cols = [col for col in df_train_filtered.columns if col in num_cols]
cat_cols = [col for col in df_train_filtered.columns if col in cat_cols]

In [ ]:
# cap outliers in the numeric columns
df_train_filtered[num_cols] = df_train_filtered[num_cols].apply(std_dev_cap_outliers, axis=0)

In [ ]:
df_train_filtered.describe()

In [ ]:
# Validate previous Univariable and Bivariable squewness
univariate(df_train_filtered, 'offnet_mou_6')
bivariate(df_train_filtered, 'spl_og_mou_6', 'churn')

#### **Preparing the Data for Modeling**

In [ ]:
# change churn to numeric
df_train_filtered['churn'] = pd.to_numeric(df_train_filtered['churn'])

#### **Splitting TRAIN data into Train Test**

In [ ]:
# divide data into train and test
X = df_train_filtered.drop("churn", axis = 1)
y = df_train_filtered.churn
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 4, stratify = y)

In [ ]:
X_TEST_CSV = df_test_filtered

In [ ]:
# print shapes of train and test sets
X_train.shape
y_train.shape
X_test.shape
y_test.shape
X_TEST_CSV.shape

#### **Aggregating the Categorical columns**

In [ ]:
train = pd.concat([X_train, y_train], axis=1)

In [ ]:
# Replace categories with aggregated values in each categorical column
mapping = {'night_pck_user_6' : {-1: train.groupby('night_pck_user_6').churn.mean()[-1], 0: train.groupby('night_pck_user_6').churn.mean()[0], 1: train.groupby('night_pck_user_6').churn.mean()[1]},
           'night_pck_user_7' : {-1: train.groupby('night_pck_user_7').churn.mean()[-1], 0: train.groupby('night_pck_user_7').churn.mean()[0], 1: train.groupby('night_pck_user_7').churn.mean()[1]},
           'night_pck_user_8' : {-1: train.groupby('night_pck_user_8').churn.mean()[-1], 0: train.groupby('night_pck_user_8').churn.mean()[0], 1: train.groupby('night_pck_user_8').churn.mean()[1]},
           'fb_user_6'        : {-1: train.groupby('fb_user_6').churn.mean()[-1], 0: train.groupby('fb_user_6').churn.mean()[0], 1: train.groupby('fb_user_6').churn.mean()[1]},
           'fb_user_7'        : {-1: train.groupby('fb_user_7').churn.mean()[-1], 0: train.groupby('fb_user_7').churn.mean()[0], 1: train.groupby('fb_user_7').churn.mean()[1]},
           'fb_user_8'        : {-1: train.groupby('fb_user_8').churn.mean()[-1], 0: train.groupby('fb_user_8').churn.mean()[0], 1: train.groupby('fb_user_8').churn.mean()[1]}
          }
X_train.replace(mapping, inplace = True)
X_test.replace(mapping, inplace = True)

# for TEST
X_TEST_CSV.replace(mapping, inplace = True)

In [ ]:
# Replace categories with aggregated values in each categorical column for TEST
X_TEST_CSV.replace(mapping, inplace = True)

In [ ]:
# check data type of categorical columns - make sure they are numeric
X_train[[col for col in cat_cols if col not in ['churn']]].info()

In [ ]:
#for TEST
X_TEST_CSV[[col for col in cat_cols]].info()

#### **PCA - Principal Component Analysis**

In [ ]:
# Apply PCA to train data
pca = Pipeline([('scaler', StandardScaler()), ('pca', PCA())])

In [ ]:
pca.fit(X_train)
churn_pca = pca.fit_transform(X_train)

In [ ]:
# Extract PCA model from pipeline
pca = pca.named_steps['pca']

# PCA components
print(pd.Series(np.round(pca.explained_variance_ratio_.cumsum(), 4)*100))

In [ ]:
# Plot feature variance
features = range(pca.n_components_)
cumulative_variance = np.round(np.cumsum(pca.explained_variance_ratio_)*100, decimals=4)
plt.figure(figsize=(175/20, 100/20)) # 100 elements on y-axis; 175 elements on x-axis; 20 is normalising factor
plt.plot(cumulative_variance)

#### **Observations:**
* 60 components explain 92.83% variance
* 80 components explain 97.18% variance
* 100 components explain 99.45% variance

#### **Model Building**

*Implementing the Model using Logistic Regression, Random Forest, CrossValidation from SciKit Learn*

##### **PCA and Logistic Regression**

In [ ]:
# Create Pipeline with Scaler, PCA, and modeling with LogisticRegression
PCA_VARS = 100
steps = [('scaler', StandardScaler()),
         ("pca", PCA(n_components=PCA_VARS)),
         ("logistic", LogisticRegression(class_weight = 'balanced'))
        ]
pipeline_pca_rl = Pipeline(steps)

In [ ]:
# fit model
pipeline_pca_rl.fit(X_train, y_train)

# check score on train data
pipeline_pca_rl.score(X_train, y_train)

#### **Evaluate on train_test data**

In [ ]:
# predict churn on test data
y_pred = pipeline_pca_rl.predict(X_test)

# create onfusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Check Precision, Accuracy, Recall and F1-Score
print("Precision: ", round(precision_score(y_test, y_pred),4))
print("Accuracy: ",  round(accuracy_score(y_test, y_pred),4))
print("Recall: ",    round(recall_score(y_test, y_pred),4))
print("F1-Score: ",  round(f1_score(y_test, y_pred),4))

# Check area under curve
y_pred_prob = pipeline_pca_rl.predict_proba(X_test)[:, 1]
print("AUC:    \t", round(roc_auc_score(y_test, y_pred_prob),4))

#### Evaluate on TEST_CSV data

In [ ]:
# predict churn on test_csv data
y_pred_test_csv_lr = pipeline_pca_rl.predict(X_TEST_CSV)

In [ ]:
#creating the file to test in kaggle
#y_rf = pd.DataFrame(y_pred_test_csv_lr)
#result = pd.concat([df_test_unseen.id, y_rf], axis=1, ignore_index=True)
#result = result.rename(columns={0: "id", 1: "churn_probability"})
#result.to_csv(RESULT_TEST_FILEPATH, index=False)
#result
#kaggle score is 0.91390

#### Hyperparameter Tuning for PCA and Logistic Regression

In [ ]:
# class imbalance
y_train.value_counts() / y_train.shape

In [ ]:
# PCA
pca = PCA()

# Logistic Regression - the class weight is used to handle class imbalance
# It adjusts the cost function
logistic = LogisticRegression(class_weight={0: 0.1, 1: 0.9})

# Create pipeline
steps = [("scaler", StandardScaler()), 
         ("pca", pca),
         ("logistic", logistic)
        ]

# Compile Pipeline
pipeline_pca_rl_tunned = Pipeline(steps)

# Hyperparameter Space
params = {'pca__n_components': [60, 80], 'logistic__C': [0.1, 0.5, 1, 2, 3, 4, 5, 10], 'logistic__penalty': ['l1', 'l2']}

# Create 5 Folds
folds = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 4)

# create gridsearch object
rl_model_tunned = GridSearchCV(estimator=pipeline_pca_rl_tunned, cv=folds, param_grid=params, scoring='roc_auc', n_jobs=-1, verbose=1)

In [ ]:
# Fit Model
rl_model_tunned.fit(X_train, y_train)

In [ ]:
# Cross Validation Results
pd.DataFrame(rl_model_tunned.cv_results_)

In [ ]:
# Print Best Hyperparameters
print("Best AUC: ", rl_model_tunned.best_score_)
print("Best HyperParameters: ", rl_model_tunned.best_params_)

In [ ]:
# Predict Churn on Train.Test Data
y_pred = rl_model_tunned.predict(X_test)

# Create Confusion Matrix again
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Check Precision, Accuracy, Recall and F1-Score
print("Precision: ", round(precision_score(y_test, y_pred),4))
print("Accuracy: ",  round(accuracy_score(y_test, y_pred),4))
print("Recall: ",    round(recall_score(y_test, y_pred),4))
print("F1-Score: ",  round(f1_score(y_test, y_pred),4))

# Check area under curve
y_pred_prob = rl_model_tunned.predict_proba(X_test)[:, 1]
print("AUC:    \t", round(roc_auc_score(y_test, y_pred_prob),4))

#### Evaluate on TEST_CSV data

In [ ]:
# predict churn on test_csv data
y_pred_test_csv_lr_tunned = rl_model_tunned.predict(X_TEST_CSV)

In [ ]:
#creating the file to test in kaggle
#y_rf = pd.DataFrame(y_pred_test_csv_lr_tunned)
#result = pd.concat([df_test_unseen.id, y_rf], axis=1, ignore_index=True)
#result = result.rename(columns={0: "id", 1: "churn_probability"})
#result.to_csv(RESULT_TEST_FILEPATH, index=False)
#result
#kaggle score is -

#### Random Forest

In [ ]:
# Random Forest
## - The class weight is used to handle class imbalance - it adjusts the cost function
forest = RandomForestClassifier(class_weight={0:0.1, 1: 0.9}, n_jobs = -1)

# Hyperparameter space
params = {"criterion": ['gini', 'entropy'], "max_features": ['auto', 0.4]}

# Create 5 folds
folds = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 4)

# create gridsearch object
rf_model = GridSearchCV(estimator=forest, cv=folds, param_grid=params, scoring='roc_auc', n_jobs=-1, verbose=1)

In [ ]:
# fit model
rf_model.fit(X_train, y_train)

In [ ]:
# print best hyperparameters
print("Best AUC: ", rf_model.best_score_)
print("Best hyperparameters: ", rf_model.best_params_)

In [ ]:
# predict churn on test data
y_pred = rf_model.predict(X_test)

# create onfusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Check Precision, Accuracy, Recall and F1-Score
print("Precision: ", round(precision_score(y_test, y_pred), 4))
print("Accuracy: ",  round(accuracy_score(y_test, y_pred), 4))
print("Recall: ",    round(recall_score(y_test, y_pred), 4))
print("F1-Score: ",  round(f1_score(y_test, y_pred), 4))

# Check area under curve
y_pred_prob = rf_model.predict_proba(X_test)[:, 1]
print("AUC:    \t", round(roc_auc_score(y_test, y_pred_prob),4))

#### Evaluate on TEST_CSV data

In [ ]:
# predict churn on test_csv data
y_pred_test_csv_rf = rf_model.predict(X_TEST_CSV)

In [ ]:
#creating the file to test in kaggle
#y_rf = pd.DataFrame(y_pred_test_csv_rf)
#result = pd.concat([df_test_unseen.id, y_rf], axis=1, ignore_index=True)
#result = result.rename(columns={0: "id", 1: "churn_probability"})
#result.to_csv(RESULT_TEST_FILEPATH, index=False)
#result
#kaggle score is -

#### **Observations:**
* The best model is Random Forest with better Scores than LogisticRegression.

#### **Choosing best features**

In [ ]:
# run a random forest model on train data
max_features = int(round(np.sqrt(X_train.shape[1])))    # number of variables to consider to split each node
print(max_features)

rf2_model = RandomForestClassifier(n_estimators=100, max_features=max_features, class_weight={0:0.1, 1: 0.9}, oob_score=True, random_state=4, verbose=1)

In [ ]:
# Fit Model
rf2_model.fit(X_train, y_train)

In [ ]:
# OOB Score
rf2_model.oob_score_

In [ ]:
len(X_train.columns)

In [ ]:
# predict churn on test data
y_pred = rf2_model.predict(X_test)

# create confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

# Check Precision, Accuracy, Recall and F1-Score
print("Precision: ", round(precision_score(y_test, y_pred),4))
print("Accuracy: ",  round(accuracy_score(y_test, y_pred),4))
print("Recall: ",    round(recall_score(y_test, y_pred),4))
print("F1-Score: ",  round(f1_score(y_test, y_pred),4))

# Check area under curve
y_pred_prob = rf2_model.predict_proba(X_test)[:, 1]
print("AUC:    \t", round(roc_auc_score(y_test, y_pred_prob),4))

#### Feature Importance

In [ ]:
# Predictors
features = df_train_filtered.drop('churn', axis=1).columns

# Feature_Importance
importance = rf2_model.feature_importances_

# Create Dataframe
feature_importance = pd.DataFrame({'variables': features, 'importance_percentage': importance * 100})
feature_importance = feature_importance[['variables', 'importance_percentage']]

# Sort Features
feature_importance = feature_importance.sort_values('importance_percentage', ascending=False).reset_index(drop=True)
print("Sum of importance=", feature_importance.importance_percentage.sum())

feature_importance

#### Extracting Top 20 features

In [ ]:
# extract top 'n' features
top_n = 20
top_features = feature_importance.variables[0:top_n]

In [ ]:
# plot feature correlation
plt.rcParams["figure.figsize"] = (10,10)
mycmap = sns.diverging_palette(199, 359, s=99, center="light", as_cmap=True)
sns.heatmap(data=X_train[top_features].corr(), center=0.0, cmap='YlGnBu')

In [ ]:
top_features

In [ ]:
X_train = X_train[top_features]
X_test = X_test[top_features]

In [ ]:
# Logistic Regression
steps = [('scaler', StandardScaler()), 
         ("logistic", LogisticRegression(class_weight={0:0.1, 1:0.9}))
        ]

# compile pipeline
logistic = Pipeline(steps)

# hyperparameter space
params = {'logistic__C': [0.1, 0.5, 1, 2, 3, 4, 5, 10], 'logistic__penalty': ['l1', 'l2']}

# create 5 folds
folds = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 4)

# create gridsearch object
model = GridSearchCV(estimator=logistic, cv=folds, param_grid=params, scoring='roc_auc', n_jobs=-1, verbose=1)

In [ ]:
# Fit Model
model.fit(X_train, y_train)

In [ ]:
# Print best hyperparameters
print("Best AUC: ", model.best_score_)
print("Best hyperparameters: ", model.best_params_)

In [ ]:
X_train.columns

#### Prepare the Test.csv Predictions file for Kraggle

In [ ]:
#y_lr = pd.DataFrame(y_pred_test_csv_lr)
#y_lr_tunned = pd.DataFrame(y_pred_test_csv_lr_tunned) 
y_rf = pd.DataFrame(y_pred_test_csv_rf)

X_TEST_CSV.head()
df_test_unseen.head()

In [ ]:
result = pd.concat([df_test_unseen.id, y_rf], axis=1, ignore_index=True)
result = result.rename(columns={0: "id", 1: "churn_probability"})

In [ ]:
# Saving the result of the RandomForest model with the TEST Data
result.to_csv(RESULT_TEST_FILEPATH, index=False)

In [ ]:
result

# Conclusions and Observations

In [ ]:
## Comments
# * The best model is RandomForest with perfect scores 1.0 with the testing.
# * Preprocessing the data is important.
# * Kraggle Accuracy:  -
# Since the submition to Kraggle gave a 0.94374 Accuracy Score, seems that the Random Fores model overfitted.
# This can be given the data rows that are eliminated from the TRAIN Data, we do not have a treatement of similar rows in TEST_CSV data.

## Top 20 Features:
1. roam_ic_mou_8
2. roam_og_mou_8
3. total_ic_mou_8
4. total_og_mou_8
5. loc_og_mou_8
6. last_day_rch_amt_8
7. total_rech_amt_8
8. loc_ic_mou_8
9. loc_ic_t2m_mou_8
10. av_rech_amt_data_8
11. arpu_8
12. std_ic_mou_8
13. max_rech_amt_8
14. onnet_mou_8
15. vol_2g_mb_8
16. loc_og_t2t_mou_8
17. loc_ic_t2t_mou_8
18. loc_og_t2c_mou_8
19. max_rech_data_8
20. arpu_7